[project]
name = "repl-nix-sudan-err-chatbot-nextjs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "opencv-python>=4.10.0.84",
]
